[package]
authors = ["Ben Lovy <ben@deciduously.com>"]
edition = "2018"
name = "deciduously-com"
version = "0.1.0"
[dependencies]
futures = "*"
hyper = "0.13"
lazy_static = "1.4"
log = "0.4"
pretty_env_logger = "0.3"
structopt = "0.3"
[dependencies.tokio]
version = "0.2"
features = ["full"]