[package]
authors = ["Ben Lovy <ben@deciduously.com>"]
edition = "2018"
name = "deciduously-com"
version = "1.0.0"

[dependencies]
askama = "0.9"
flate2 = "1.0"
hyper = "0.13"
lazy_static = "1.4"
log = "0.4"
pretty_env_logger = "0.4"
serde = "1.0"
serde_derive = "1.0"
structopt = "0.3"
toml = "0.5"

[dependencies.tokio]
features = ["full"]
version = "0.2"

[dev-dependencies]
pretty_assertions = "0.6"