[header]
first_name = "Ben"
last_name = "Lovy"
email = "bendlovy@gmail.com"
subtitle = "Software Developer"

[[header.links]]
icon = "github.svg"

[header.links.hyperlink]
name = "deciduously"
target = "https://github.com/deciduously"

[[header.links]]
icon = "dev-badge.svg"

[header.links.hyperlink]
name = "deciduously"
target = "https://dev.to/deciduously"

[[header.links]]
icon = "linkedin-icon.svg"

[header.links.hyperlink]
name = "bendlovy"
target = "https://www.linkedin.com/in/benlovy/"

[intro]
one_liner = "Entry-level software developer with a life-long passion for creative problem solving."
about = "Eager to apply my self-learned programming knowledge, utilizing my background in high-intensity, fast paced work environments to bring strong positive energy mixed with technical expertise to the team and product."
skills = "Quick to internalize new concepts.  Highly motivated and resourceful self-learner.  Thrives in fast-paced, high-intensity environments without sacrificing attention to detail. Effective, diplomatic communicator in difficult or delicate situations."
techs = "Productive when working with a range of languages including C++, JavaScript, TypeScript, Python, and Rust, as well as modern ecosystem tools such as Git/GitHub, Linux, Docker, GraphQL vs RESTful API design, test-driven development."

[header.address]
street = "37 Capitol St"
line2 = "Unit 1"

[header.address.locality]
name = "Watertown"
postal_code = "02472"

[header.address.locality.state]
abbreviation = "MA"
full_name = "Massachussetts"
country = "United States"

[[education]]
name = "Champlain College"

[education.address]
street = " 163 South Willard St"

[education.address.locality]
name = "Burlington"
postal_code = "05401"

[education.address.locality.state]
abbreviation = "VT"
full_name = "Vermont"
country = "United States"

[[education.degrees]]
gpa = 4.0
expected = true
degree_type = "Cert"
subject = "C++ Programming"

[education.degrees.graduation_date]
year = 2020
month = "May"

[[education.degrees]]
gpa = 4.0
expected = true
degree_type = "BS"
subject = "Software Development"

[education.degrees.graduation_date]
year = 2021
month = "May"

[[projects]]
name = "Mifkad"
synopsis = "Full-stack web app for attendance collection, currently in production.  ReasonReact UI, Rust/actix_web backend."

[[projects]]
name = "Blispr"
synopsis = "Toy lisp interpreter built in Rust, translated from C.  Includes partially applied user-defined lambdas."

[[projects]]
name = "Music"
synopsis = "CLI synthesizer and procedural melody generater in Rust.  Provides simple abstracted API over music theory concepts."

[[projects]]
name = "deciduously-com"
synopsis = "This website and CV is built with a DIY static site generator and API server, using the hyper HTTP library for Rust."

[[employment]]
title = "Programming Intern I"
employer = "MousePaw Media"
current = true
bullets = [
  "Design, implement, and test new libraries and features for a suite of vector animation-based content creation software.",
  "Collaborate with a team of developers via Git and Phabricator.",
  "Primary project: Ratscript, a embedded scripting langauge - C++17.",
  "Secondary project: SIMPLExpress, an pattern matching expression parser for the Ratscript lexer - C++17."
]

[employment.begin_date]
year = 2020
month = "Jan"

[employment.address]
street = "Remote"

[employment.address.locality]
name = "Couer d'Alene"
postal_code = "83814"

[employment.address.locality.state]
abbreviation = "ID"
full_name = "Idaho"
country = "United States"

[[employment]]
title = "Accounts Receivable/Billing"
employer = "JCC Greater Boston"
current = true
bullets = [
  "Accurately completed daily billing/receiving tasks, interfacing with our accounting and membership database software.",
  "Created and maintained extensive documentation of job tasks as they pertain to the software.",
  "Leveraged creative solutions to automation problems to reclaim administrative time, using a mix of Rust, Windows batch scripts, and Excel macros."
]

[employment.begin_date]
year = 2018
month = "Apr"

[employment.address]
street = "333 Nahanton St"

[employment.address.locality]
name = "Newton"
postal_code = "02459"

[employment.address.locality.state]
abbreviation = "MA"
full_name = "Massachussetts"
country = "United States"

[[employment]]
title = "Administrative Assistant"
employer = "JCC Greater Boston"
current = false
bullets = [
  "Organized and staffed educators, maintaining state-mandated child/staff ratios.",
  "Tuned standard operating procedures to accommodate a rapidly growing student body.",
  "Liaison between our educators, clients, JCC community, and 3rd party vendors."
]

[employment.begin_date]
year = 2017
month = "Aug"

[employment.end_date]
year = 2018
month = "Apr"

[employment.address]
street = "333 Nahanton St"

[employment.address.locality]
name = "Newton"
postal_code = "02459"

[employment.address.locality.state]
abbreviation = "MA"
full_name = "Massachussetts"
country = "United States"

[[employment]]
title = "Shift Leader"
employer = "Peet's Coffee"
current = false
bullets = [
  "Monitored day to day product movement and ensured weekly restock minimize waste.",
  "Oversaw staff behavior and customer affect.",
  "Created and enforced standard operating procedures to maximize profits and customer engagement."
]

[employment.begin_date]
year = 2015
month = "Aug"

[employment.end_date]
year = 2017
month = "Apr"

[employment.address]
street = "853 Broadway"

[employment.address.locality]
name = "New York"
postal_code = "10003"

[employment.address.locality.state]
abbreviation = "NY"
full_name = "New York"
country = "United States"

[[employment]]
title = "Operations Manager - Washington, DC"
employer = "ZIRX"
current = false
bullets = [
  "Recruited, trained, and managed a team of 35-40 independent contractors.  Ensured proper day-to-day coverage needs were met and addressed all local operational concerns swiftly and appropriately.",
  "Communicate between QA and production environments.  Retrain ground stuff with new updates, allowing for rapid iteration of product.",
  "Liaison between remote HQ and my local market, leveraging data visualization techniques to track growth to ensure consistent expansion."
]

[employment.begin_date]
year = 2014
month = "Aug"

[employment.end_date]
year = 2015
month = "Jul"

[employment.address]
street = "350 Townsend St"

[employment.address.locality]
name = "San Francisco"
postal_code = "94107"

[employment.address.locality.state]
abbreviation = "CA"
full_name = "California"
country = "United States"
