[[projects]]
name = "Chip8"
repo = "https://github.com/deciduously/chip8"
demo = "https://deciduously.github.io/chip8"
language = "Rust"
synopsis = "A Chip-8 emulator targeting SDL2 and/or WebAssembly"

[[projects]]
name = "Hunt the Wumpus"
repo = "https://github.com/deciduously/hunt-the-wumpus"
demo = "https://deciduously.github.io/hunt-the-wumpus/"
language = "Rust/Yew"
synopsis = "A WebAssembly Hunt The Wumpus game."

[[projects]]
name = "Dots"
repo = "https://github.com/deciduously/dots"
demo = "https://deciduously.github.io/dots/"
language = "Rust"
synopsis = "A WebAssembly clone of Boomshine."

[[projects]]
name = "Mazes"
repo = "https://github.com/deciduously/mazes"
demo = "https://deciduously.github.io/mazes/"
language = "TypeScript/Vue"
synopsis = "Maze Generator and Solver"