name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Generate Style
      run: npm install && npm run style
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag deciduously-com:$(date +%s)
